# Generated by Django 5.2.6 on 2025-09-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipclone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(max_length=100),
        ),
    ]
